var homepage = "http://fandiadinata.com/desa";

database_berita = [
    {
        "id" : 33,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  32,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  31,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  30,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 272,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  29,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21320,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  28,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 11328,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  27,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  26,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  25,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  24,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  23,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  22,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  21,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21327,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  20,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  19,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  18,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  17,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21320,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  16,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 1852,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  15,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  14,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 22530,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  13,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 1863,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  12,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  11,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 2580,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  10,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  9,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  8,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 2085,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  7,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  6,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  5,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  4,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" : 3,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  2,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "id" :  1,
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
  ];