database_berita = [
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 272,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21320,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 11328,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21327,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18132,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 21320,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 1852,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 22530,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 1863,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 2580,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 2085,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 27,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "12.27",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 20,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "13.00",
        "link" : "contoh-postingan.html",
    },
    {
        "judul" : "Contoh Postingan Pertama Untuk Desa Jetis Lor, Nawangan, Pacitan",
        "penulis" : "Penulis Anonim",
        "tanggal" : 18,
        "bulan" : 1,
        "tahun" : 2022,
        "jam" : "24.00",
        "link" : "contoh-postingan.html",
    },
  ];